controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: admin
