name: Demo

on:
  [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.10.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Upload
        run: |
          rsync -e "ssh -p ${{ secrets.SSH_PORT }}" --archive --compress --delete . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/web

      - name: Composer Install
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '${{ secrets.DEPLOY_PATH }}/.deploy/composer.sh'

      - name: Build assets
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '${{ secrets.DEPLOY_PATH }}/.deploy/assets.sh'

      - name: Run scripts
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '${{ secrets.DEPLOY_PATH }}/.deploy/scripts.sh'
